DROP TABLE SYSFD;

CREATE TABLE SYSFD
(
  SEQ    NUMBER,
  PATH   VARCHAR2(255 BYTE)                     NOT NULL,
  ORGNM  VARCHAR2(255 BYTE)                     NOT NULL,
  SAVNM  VARCHAR2(64 BYTE)                      NOT NULL,
  EXT	 VARCHAR2(32 BYTE),
  MIME   VARCHAR2(64 BYTE),
  LEN    NUMBER									DEFAULT 0,
  ACC    NUMBER                                 DEFAULT 0,
  DEL    CHAR(1 BYTE)                           DEFAULT 'N'			NOT NULL		CHECK( DEL IN ( 'Y', 'N' ) )
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SYSFD.SEQ IS '관리번호';

COMMENT ON COLUMN SYSFD.ORGNM IS '원본파일명';

COMMENT ON COLUMN SYSFD.SAVNM IS '저장파일명';

COMMENT ON COLUMN SYSFD.PATH IS '저장경로';

COMMENT ON COLUMN SYSFD.MIME IS 'MIME-TYPE';

COMMENT ON COLUMN SYSFD.LEN IS '파일용량';

COMMENT ON COLUMN SYSFD.ACC IS '접근횟수';

COMMENT ON COLUMN SYSFD.DEL IS '삭제여부(Y:삭제,N:미삭제)';

CREATE UNIQUE INDEX PK_SYSFD ON SYSFD
(SEQ)
LOGGING
NOPARALLEL;

ALTER TABLE SYSFD ADD (
  CONSTRAINT PK_SYSFD
 PRIMARY KEY
 (SEQ));

CREATE SEQUENCE SQ_SYSFD
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE 
NOCYCLE 
NOORDER;